### PR TITLE
Fix showing of server side validation error response in RLP & DNS cre…

### LINKED ISSUE #58: Implement and wire up a validation helper to validate policy fields before attempting to save the policy
Ideally part of this helper https://github.com/Kuadrant/console-plugin/blob/main/src/utils/createResource.tsx

If server side validation is relied on, the promise rejection from https://github.com/openshift/console/blob/master/frontend/packages/console-dynamic-plugin-sdk/docs/api.md#k8screateresource may be useable to do this.

### PR DESCRIPTION
**Pull request by david-martin**
…ate views

closes #58 

The Create button on the DNS & RLP pages is disabled until the name, namespace and targetRef are set.
After that, if there's an error when you click create, it will show an alert box below the form (see screenshot for example)

The changes also include the removal of the custom save function for DNSPolicy via the yaml editor as it isn't required (it was originally added as I thought it was needed to convert matchLabels from an object to an array, and back again at the right time for yaml saving, but that's only the case for the form view). Making this change allows the yaml editor to fall back to the built in save function for that component, which handles creation and showing validation errors.

image

TODO:

- [x] client side validation of resource namespace being non-empty, as an empty namespace causes the k8sCreate fn to POST to a slightly different url (without the namespace in it) which results in a 404, rather than a 422 with a validation error response
- [x] client side validation of resource name, as it's a standard field to have on all resources, and can easily be reused across all create views (input text type)
- [x] see if it's possible to highlight validation errors inline on specific fields in a generic way based on the 422 validation error response (or at the very least, have it for name & namespace)

### CODE REVIEW

**Comment by jasonmadigan** [comment]
👀

File: src/components/KuadrantDNSPolicyCreatePage.tsx [hunk 1]
```diff
@@ -1,6 +1,5 @@
 import * as React from 'react';
 import Helmet from 'react-helmet';
-import yaml from 'js-yaml';
```
Comment (jasonmadigan) [inline src/components/KuadrantDNSPolicyCreatePage.tsx:3]: Can probably drop from package.json now

File: src/components/KuadrantDNSPolicyCreatePage.tsx [hunk 2]
```diff
@@ -122,39 +126,10 @@ const KuadrantDNSPolicyCreatePage: React.FC = () => {
...
-            })),
-          },
-        });
-        setHealthCheck(parsedYaml.spec.healthCheck || healthCheck);
-      }
-    } catch (error) {
-      console.error('Error parsing YAML:', error);
-    }
-    handleSubmit();
-  };
```
Comment (jasonmadigan) [inline src/components/KuadrantDNSPolicyCreatePage.tsx:155]: 🫡

File: src/components/KuadrantRateLimitPolicyCreatePage.tsx [hunk 3]
```diff
@@ -316,13 +312,22 @@ const KuadrantRateLimitPolicyCreatePage: React.FC = () => {
...
-            <Alert
-              variant="info"
-              isInline
-              title="To set defaults, overrides, and more complex limits, use the YAML view."
-            />
+            <AlertGroup className="kuadrant-alert-group">
+              <Alert
+                variant="info"
+                isInline
+                title="To set defaults, overrides, and more complex limits, use the YAML view."
```
Comment (jasonmadigan) [inline src/components/KuadrantRateLimitPolicyCreatePage.tsx:319]: realise this is from an earlier PR, but an i18n string here would be good

**Review by jasonmadigan — COMMENTED** [review]
Couple of small bits

File: src/components/KuadrantDNSPolicyCreatePage.tsx (hunk 1 above)
Comment (david-martin) [reply src/components/KuadrantDNSPolicyCreatePage.tsx:3]: yes, will remove as it's not used elsewhere.
It might get re-introduced with #59
